window.products = [
    {
        code: '8017',
        name: 'WINDGUARD OVERCOAT',
        price: 180,
        category: 'outerwear',
        imageUrl: '/unComfort/img/8017_gray.jpg',
        materials: "Shell: 77% Cotton, 23% Nylon/ Lining: 100% Polyester/ Hood: 100% Nylon/ Hood: Storage Bag: 100% Polyester/ Side Pocket Fabric: Outer Layer: 100% Polyester/ Side Pocket Fabric: Inner Layer: 77% Cotton, 23% Nylon",
        colours: ['gray', 'brown'],
        sizes: ['XS','S', 'M', 'L', 'XL'],
    },
    {
        code: '8004',
        name: 'RELAXED FLEECE',
        price: 140,
        category: 'hoodies',
        imageUrl: '/unComfort/img/8004_gray.jpg',
        materials: "FunBody: 51% Polyester, 49% Cotton/ Pocket Lining: 100% Polyester Fabric: 100% Polyester",
        colours: ['gray', 'brown'],
        sizes: ['XS','S', 'M', 'L', 'XL'],
    },
    {
        code: '8010',
        name: 'RELAXED COLLARED',
        price: 95,
        category: 'tees',
        imageUrl: '/unComfort/img/8010_beige.jpg',
        materials: "Fabric details: 53% Modal, 47% Cotton Function details: Sheer: Not Sheer(Only 00 White is slightly sheer) Fit: Relaxed",
        colours: ['beige', 'black', 'blue', 'white'],
        sizes: ['XXS','XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8001',
        name: 'LIGHT STRINGER',
        price: 40,
        category: 'singlets',
        imageUrl: '/unComfort/img/8001_black.jpg',
        materials: 'Fabric details: 73% Cotton, 27% Polyester ( 27% Made From Recycled Polyester )Function details: Sheer: Not Sheer(Only 00 White is slightly sheer) Fit: Fitted Pockets: No Pockets Fabric: 100% Polyester',
        colours: ['black', 'gray'],
        sizes: ['XXS','XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8023',
        name: 'KNEECUT JORTS',
        price: 100,
        category: 'shorts',
        imageUrl: '/unComfort/img/8023_black.jpg',
        materials: 'Fabric details: Body: 100% Cotton/ Pocket Lining: 65% Polyester, 35% Cotton Function details: Fit: Loose Pockets: With Pockets Fabric: 100% Polyester',
        colours: ['black', 'blue'],
        sizes: ['XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8003',
        name: 'WIDECUT CHINO',
        price: 140,
        category: 'bottoms',
        imageUrl: '/unComfort/img/8003_black.jpg',
        materials: 'Fabric details: Body: 77% Cotton, 23% Polyester/ Pocket Lining: 65% Polyester, 35% Cotton Function details: Fit: Wide Pockets: With Pockets Fabric: 100% Polyester',
        colours: ['black', 'blue'],
        sizes: ['XXS','XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8002',
        name: 'UTILITY BAG',
        price: 80,
        category: 'accessories',
        imageUrl: '/unComfort/img/8002_black.jpg',
        materials: 'Fabric details: Shell: 100% Nylon/ Lining: 100% Polyester/ Filling: 100% Polyester/ Shoulder: 100% Polyester',
        colours: ['black', 'olive'],
        sizes: ['ONE SIZE']
    },
    {  
        code: '8005',
        name: 'RELAXED ANKLE TRACKS',
        price: 70,
        category: 'trackies',
        imageUrl: '/unComfort/img/8005_black.jpg',
        materials: 'Fabric details: Body: 100% Cotton/ Pocket Lining: 65% Polyester, 35% Cotton Function details: Fit: Wide Pockets: With Pockets Fabric: 100% Polyester',
        colours: ['black', 'gray', 'blue'],
        sizes: ['XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8009',
        name: 'BUCKET HAT',
        price: 50,
        category: 'accessories',
        imageUrl: '/unComfort/img/8009_black.jpg',
        materials: 'Shell: Base: 100% Nylon/ Coating: Polyurethane/ Filling: 100% Polyester/ Lining: 100% Cotton',
        colours: ['black', 'beige'],
        sizes: ['ONE SIZE']
    },
    {
        code: '8015',
        name: 'WINDGUARD PUFFER',
        price: 160,
        category: 'outerwear',
        imageUrl: '/unComfort/img/8015_black.jpg',
        materials: 'Fabric details: Body: 100% Polyester/ Lining: 100% Polyester/ Hood: 100% Polyester/ Hood: Storage Bag: 100% Polyester/ Side Pocket Fabric: Outer Layer: 100% Polyester/ Side Pocket Fabric: Inner Layer: 77% Cotton, 23% Nylon',
        colours: ['black', 'wine', 'olive'],
        sizes: ['XXS', 'XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8011',
        name: 'LIGHTWEIGHT PARKA',
        price: 150,
        category: 'hoodies',
        imageUrl: '/unComfort/img/8011_black.jpg',
        materials: 'Base: 100% Polyester ( 50% Made From Recycled Polyester )/ Coating: Polyurethane',
        colours: ['black', 'blue', 'orange', 'olive'],
        sizes: ['XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8007',
        name: 'HEAVYWEIGHT TEE',
        price: 65,
        category: 'tees',
        imageUrl: '/unComfort/img/8007_white.jpg',
        materials: 'Fabric details: Body: 53% Cotton, 47% Polyester ( 30% Made From Recycled Polyester )/ Lining: 100% Polyester',
        colours: ['white', 'gray', 'wine', 'black', 'blue'],
        sizes: ['XXS', 'XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8020',
        name: 'RELAXED CARGOS',
        price: 120,
        category: 'bottoms',
        imageUrl: '/unComfort/img/8020_black.jpg',
        materials: 'Fabric details: Body: 100% Cotton/ Pocket Lining: 65% Polyester, 35% Cotton Function details: Fit: Wide Pockets: With Pockets Fabric: 100% Polyester',
        colours: ['black', 'white', 'olive', 'beige'],
        sizes: ['XS','S', 'M', 'L', 'XL', 'XXL'],
    },
    {
        code: '8016',
        name: 'UTILITY SHORTS',
        price: 90,
        category: 'shorts',
        imageUrl: '/unComfort/img/8016_blue.jpg',
        materials: 'Fabric details: Body: 100% Cotton/ Pocket Lining: 65% Polyester, 35% Cotton Function details: Fit: Wide Pockets: With Pockets Fabric: 100% Polyester',
        colours: ['black', 'blue', 'olive', 'beige'],
        sizes: ['XS','S', 'M', 'L', 'XL', 'XXL'],
    }

];
